name: Cargo Bench

on:
  push:
    branches: ['main']
    paths:
      - '.github/workflows/cargo_bench.yml'
      - 'benches/**/*.rs'
      - 'src/**/*.rs'
      - 'Cargo.lock'
      - 'Cargo.toml'
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  cargo-bench:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Nightly
        run: |
          rustup toolchain install nightly --component clippy
          rustup override set nightly

      - name: Bench
        run: |
          cargo bench
